export const START_MESSAGE = "Start using WhatsApp AI Assistant";
export const START_MESSAGE_REPLY = "Hello! 👋 I am your WhatsApp AI Assistant 🤖 I can help you with your queries. Please type your query and I will try to help you. You can generate images 🖼️ or stickers using the /image and /sticker commands"
export const BOT_PHONE_NUMBER = "+201064134160";
export const WHATSAPP_URL = `https://api.whatsapp.com/send/?phone=${BOT_PHONE_NUMBER}&text=${START_MESSAGE.replace(/ /g, "%20")}`;
export const MAX_NUMBER_OF_MESSAGES = 30;
export const SUMMARIZE_SYSTEM_MESSAGE = { content: "Summarize the conversation so far.", role: "system"}
export const WHATSAPP_MAX_TEXT_LENGTH = 4096;
export const DALLE_MAX_TEXT_LENGTH = 1000;
export const STICKER_WAIT_MESSAGE = "Hold tight! your awesome sticker is being generated ⏳";
export const IMAGE_WAIT_MESSAGE = "Hold tight! I'm generating your image ⏳🖼️";
export const STARTER_TOKENS_COUNT = 5;
export const TEXT_TOKEN_COST = 1/150;
export const TEXT_TOKEN_COST_FREE = 1/50;
export const IMAGE_TOKEN_COST = 1;
export const STICKER_TOKEN_COST = 1;
export const RATE_LIMIT_ERROR_MESSAGE = "rate_limit_exceeded";
export const RATE_LIMIT_MESSAGE = "I'm sorry, I'm currently experiencing a high volume of requests. Please try again later. 🙏";
export const GUMROAD_PAYMENT_URL = "https://gum.co/whatsapp-ai-assistant";
export const FREE_TRIAL_ENDED_MESSAGE = `Your free trial of WhatsApp AI Assistant has ended. Keep creating stickers 🎨, generating images 🖼️, and getting answers instantly by subscribing now!\n🔗 Pay here: ${GUMROAD_PAYMENT_URL}\nDon't miss out on the full experience! ✨`;
export const COULDNT_RENEW_SUBSCRIPTION_MESSAGE = `I couldn't renew your subscription. Don't worry! You can still enjoy the features by resubscribing.\n🔗 Renew your subscription here: ${GUMROAD_PAYMENT_URL}\nExplore and enjoy the full experience! ✨`;
export const TOKENS_LIMIT_EXCEEDED_MESSAGE = `Hey there! It looks like you've used up all your sticker and image generations 🚀. To keep the creativity flowing, why not consider upgrading to a higher tier?\nYou can easily upgrade by visiting ${GUMROAD_PAYMENT_URL}. Happy creating!`;