name: Deploy to Ireland

on:  #Name of the GitHub event that triggers the workflow
  push:   #On Push Event We need to take action
    branches:  #Now we need to specify the branch name
    - main   

jobs:  #Workflow run is made up of one or more jobs
  deploy_lambda:
    runs-on: ubuntu-latest  #Through which Server OS we need to Work (type of machine to run the job on)
    steps:
    #Using versioned actions 
      - uses: actions/checkout@v2  # --> Reference a specific version
      - uses: actions/setup-node@v2 # --> To Setup the Server With Node Env
        with:  
          node-version: '20' #--> Specify the Version of the Node 
      - name: Configure AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v1 #--> Setup the Credential for the AWS cli
        with:
        # Created the Secrets Under the Repo only with These Variables
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1 #--> Define Region of the AWS-CLI 
      - name: npm install
        env:
          CI: true
        run: |
          npm ci 
      - name: Zip the function code
        run: |
          zip -r function.zip .
      # - name: Check if function exists
      - name: create or update function
        run: |
          aws lambda update-function-code --function-name wagpt --zip-file fileb://function.zip